# HCFactions by drtshock and milkywayz 
# Report issues https://github.com/drtshock/HCFProblems/issues/new
# Live support http://webchat.esper.net/?channels=drtshock&prompt=1

# Made with love <3

# Debug
# Turn this on if you are having issues with something and working on resolving them.
# This will spam your console with information that is useful if you know how to read the source.
# It's suggested that you only turn this on at the direction of a developer.
debug: false

# Prevent find factions exploit
# This will help limit how many times a player can be sent a map of factions.
# Set this to the cooldown you want, in miliseconds, for a map to be shown to a player.
# If you want to log when a player violates this (only happens on chunk enter so it shouldn't be too spammy),
#   set log to true and it will be logged to console as "player tried to show a faction map too soon and triggered exploit blocker."
findfactionsexploit:
  cooldown: 2000 # in miliseconds. 2000 = 2 seconds.
  log: false

# Default Relation allows you to change the default relation for Factions.
# Example usage would be so people can't leave then make a new Faction while Raiding
#   in order to be able to execute commands if the default relation is neutral.
# This has always been neutral.
default-relation: "enemy"

# Portal Creation
# Do you want to limit portal creation?
portals:
  limit: false # will disable the below check if set to false

  # What should the minimum relation be to create a portal in territory?
  # Goes in the order of: ENEMY, NEUTRAL, ALLY, MEMBER.
  # Minimum relation allows that and all listed to the right to create portals.
  # Example: put ALLY to allow ALLY and MEMBER to be able to create portals.
  minimum-relation: MEMBER # If typed incorrectly, defaults to NEUTRAL.

# Warps
# What should be the max amount of warps that a Factoin can set?
max-warps: 5

# This is the cost section for warps.
# It will charge them each time the command would be successful. (won't charge on erroneous /f warp attempts).
# You can use decimal places here.
# If enabled is set to false, it will ignore the values.
warp-cost:
  enabled: false
  setwarp: 5.0
  delwarp: 5.0
  warp: 5.0

# Pistons
# Should we disable pistons in Faction territory? This will prevent people from doing something like:
# http://i.gyazo.com/6a1a31222e58a5d60ff341c13f6a8404.gif
disable-pistons-in-territory: false

# ToolTips
# This section is to configure tooltips for things like /f list
tooltips:

  # List
  # This shows up when someone does /f list for the top factions.
  # It will not sure up for factionless of course, just actual factions.
  # You can use color codes here.
  list:
    - "&6Leader: &f{leader}"
    - "&6Claimed: &f{chunks}"
    - "&6Raidable: &f{raidable}"
    - "&6Warps: &f{warps}"
    - "&6Members: &f{online}/{members}"

  # Show
  # This shows up when someone does /f show.
  # It adds tooltips to each player in the list here, nothing else.
  # {group} will show the players primary group if you have vault installed.
  # {balance} will show their balance if you have vault installed.
  # {lastSeen} will show human readable info on when the player was last seen, or online.
  show:
    - "&6Last Seen: &f{lastSeen}"
    - "&6Rank: &f{group}"
    - "&6Balance: &a${balance}"

# Configuration section for Scoreboards
# This will allow you to completely customize how your scoreboards look.
# Make sure that no lines are duplicates of each other otherwise only the first will display.
# Use &0-9a-f for colors and include messages in "quotes"
scoreboard:

# How long do we want scoreboards to stay if set temporarily.
  expiration: 7

# FInfo scoreboard is displayed when a player walks into a new Faction's territory.
# Scoreboard disappears after <expiration> seconds.
# Things to be replaced in this:
# {name} - viewer name. {balance} - viewer balance. {faction} faction tag (FYI: title of board is already faction tag)
# {dtr} - Factions current DTR. {maxdtr} - Max DTR that faction can have
# {land} - total claimed land (in chunks). {maxland} - how much land a faction can claim
# {members} - total members. {online} - online members. {leader} - faction's leader.
# {raidable} - true if the faction can be claimed over, otherwise false.
# {warps} - the number of warps that a faction has set. {totalOnline} - # of online players
# {alliescount} - # of allies faction has. {maxenemies} - max # of enemies faction can have.
# {maxallies} - max # of allies faction can have. {enemiescount} - how many enemies faction has.
# The title of the scoreboard will be the Faction's tag and colored according to the relation with the player's Faction.
# Commenting this section out will cause the info to appear in chat as the plugin originally did.
  finfo-enabled: false # Default to false to keep original functionality.
  finfo:
    - "&3Members"
    - "{online}/{members}"
    - "&4DTR"
    - "{dtr}/{maxdtr}&r"
    - "&9Raidable: {raidable}"
    - "&bLand"
    - "{land}/{maxland}&f"

# Default board that will always show up if a player wants it to.
# This can show any arbitrary text or you can use a lot of variables to replace things.
# {name} - viewer name. {balance} - viewer balance. {faction} - faction tag
# {dtr} - Factions current DTR. {maxdtr} - Max DTR that faction can have
# {land} - total claimed land (in chunks). {maxland} - how much land a faction can claim
# {members} - total members. {online} - online members. {leader} - faction's leader.
# {raidable} - true if the faction can be claimed over, otherwise false.
# {warps} - the number of warps that a faction has set. {totalOnline} - # of online players
# {alliescount} - # of allies faction has. {maxenemies} - max # of enemies faction can have.
# {maxallies} - max # of allies faction can have. {enemiescount} - how many enemies faction has.
#
  default-enabled: true
  default-title: "{name}" # Can use any of the values from above but this won't update once it's set (so don't set {balance}).
  default-update-interval: 5 # in seconds.

  # This will show faction prefixes colored based on relation on nametags and in the tab.
  #   The scoreboard needs to be enabled for this to work.
  default-prefixes: true

  default:
    - "&6Your Faction"
    - "{faction}"
    - "&4Faction DTR"
    - "{dtr}/{maxdtr}&r"
    - "&aLand"
    - "{land}/{maxland}&f"

# Configration section for warmups.
# Warmup times are in seconds - if a value of 0 is set, there is no warmup.
warmups:
  # Delay for /f home
  f-home: 0
  # Delay for /f warp
  f-warp: 0

# Max Relation Types
# Limits factions to having a max number of each relation.
# Setting to 0 means none allowed. -1 for disabled.
# This will have no effect on default or existing relations, only when relations are changed.
# It is advised that you set the default relation to -1 so they can always go back to that.
# Otherwise Factions could be stuck with not being able to unenemy other Factions.
max-relations:
  enabled: true
  ally: 2
  truce: 10
  neutral: -1
  enemy: 10

# WorldBorder support 
# A buffer of 0 means faction claims can go right up to the border of the world.
# The buffer is in chunks, so 1 as a buffer means an entire chunk of buffer between 
# the border of the world and what can be claimed to factions
world-border:
  buffer: 0

# Configurable f show output
#
# Variables: 
# {description} - faction description. {joining} - joining instructions. {peaceful?} - only shows if peaceful.
# {land} - how many chunks faction claimed. {maxland} - how many chunks faction can claim.
# {dtr} - current deaths to raidable value. {maxdtr} - max deaths to raidable value.
# {raidable} - raidable status. {world} - world of faction home. {x} - x coord. {y} - y coord. {z} - z coord.
# {timeleft} - time remaining on DTR freeze. {value} - total land value.
# {refund} - land refund value. {balance} - factions bank balance. {allies} - list of faction allies.
# {enemies} - list of faction enemies. {online} - list of online members. {offline} - list of offline members.
# {onlinecount} - # of online faction members, {offlinecount} - # of offline faction members.
# {factionsize} - total size of faction. {alliescount} - # of allies faction has.
# {maxallies} - max # of allies faction can have. {enemiescount} - how many enemies faction has.
# {maxenemies} - max # of enemies faction can have. {header} - the built in header string.
# {tag} - faction tag. {createDate} - time faction was created. Uses format in lang.yml for date.
#
fshow:
  - '{header}'
  - '<a>Description: <i>{description}'
  - '<a>Joining: <i>{joining}    {peaceful?}'
  - '<a>Land / Max: <i> {land} / {maxland}'
  - '<a>DTR: <i>{dtr} / {maxdtr} <a>Raidable: <i>{raidable}'
  - '<a>Faction Home: <i>{world}, {x}, {y}, {z}'
  - '<a>DTR Freeze: <i>{timeleft}'
  - '<a>Founded: <i>{createDate}'
  - '<a>This faction is permanent, remaining even with no members.'
  - '<a>Land value: <i>{value} {refund}'
  - '<a>Balanace: <i>{balance}'
  - '<a>Allies(<i>{alliescount}<a>/<i>{maxallies}<a>): {allies} '
  - '<a>Members: (<i>{onlineCount}<a>/(<i>{factionSize}<a>): {online}'

# Enable to have a minimalistic fshow
# Doesn't bother sending useless lines
hide-unused-fshow: true

# Configurable f list output
#
# Variables:
# {pagenumber} - current page number. {pagecount} - number of pages.
# {tag} - faction tag. {online} - # of members online. {factionsize} - total # of members in faction.
# {land} - how many chunks faction claimed. {maxland} - how many chunks faction can claim.
# {dtr} - current deaths to raidable value. {maxdtr} - max deaths to raidable value.
# {raidable} - raidable status. {count} - how many factionless players are online.
flist:
  header: 'Faction List {pagenumber}/{pagecount}'
  factionless: '<i>Factionless<i> {count} online'
  entry: '<a>{tag} <i>{online}/{factionsize} online, <a>Land: <i>{land} / {maxland}, <a>Raidable: {raidable}'

############################################################
# +------------------------------------------------------+ #
# |                  HardCore Factions                   | #
# +------------------------------------------------------+ #
############################################################

hcf:
  # DTR (death till raidable) will be in /f show if enabled.
  # When DTR is below 0, the faction is considered raidable
  dtr:
    # Maximum DTR a faction can have 
    max-faction-dtr: 5.5
    # How much DTR should we charge a faction for kicking a player when they are frozen
    # Set to 0 to disable penalty, but remember a faction can kick low dtr players to remain unraidable if theres no penalty!
    kick-penalty: 1.0 
    # Minimum DTR a faction can have 
    min-faction-dtr: -6.0
    # How much DTR is lost on death
    death-dtr: 1.0
    # How much DTR is replenished per faction member per minute 
    minute-dtr: 0.01
    # How much max DTR should a faction gain per player?
    # Max DTR = min(player-dtr * faction size, max-faction-dtr)
    player-dtr: .51
    # How much DTR should a solo faction get?
    # Used so solo factions can have more than 1 death before raidable.
    solo-faction: 1.01
    # After a player dies, how long should the faction not be able to regen dtr?
    # This resets on each death but does not accumulate.
    # Set to 0 for no freeze. Time is in seconds.
    dtr-freeze: 0
    # DTR Freeze background regeneration
    # False unless you want factions to gain back the DTR
    # they would have generated during their DTR freeze
    allow-background-regen: false
    # Should we let players leave a frozen faction?
    freeze-leave: false
    # Should we let players join a frozen faction?
    freeze-join: true
    # Should we let frozen factions disband?
    freeze-disband: false
  fstuck:
    # Time in seconds before teleport occurs
    delay: 60
    # list of block ids you want to rule out from f stuck
    # we check the block under, at, and two above (player head and then space above) for this block
    # if it exists in any of the 4 locations, we will skip and find a safer teleport location
    black-list:
    - 8
    - 9
    - 10
    - 11
    - 51

  # Max land a faction can have claimed
  faction-land-max: 36
  
  # How much land a faction gets per member
  land-per-player: 6

  # Allows PVP betweeen members and allys of one faction
  friendly-fire: false

  # Buffer Zone
  # Buffer Zone is an chunk area required between claims of different Factions.
  # This is default to 0 and has always been that way. Meaning Factions can have
  #   claims that border each other.
  # If this is set to 3, then Factions need to have 3 chunks between their claim
  #   and another Faction's claim.
  # It's recommended to keep this pretty low as the radius check could be a
  #   heavy operation if set to a large number.
  # If this is set to 0, we won't even bother checking which is how Factions has
  #   always been.
  buffer-zone: 0

use-old-help: false

############################################################
# +------------------------------------------------------+ #
# |                Configurable /f help                  | #
# +------------------------------------------------------+ #
############################################################

help:
  # You can change the page name to whatever you like
  # We use '1' to preserve default functionality of /f help 1
  '1':
    - '&e&m----------------------------------------------'
    - '                      &c&lHCF Help               '
    - '&e&m----------------------------------------------'
    - '&3/f create  &e>>  &7Create your own faction'
    - '&3/f who      &e>>  &7Show factions info'
    - '&3/f tag      &e>>  &7Change faction tag'
    - '&3/f join     &e>>  &7Join faction'
    - '&3/f list      &e>>  &7List all factions'
    - '&e&m--------------&r &2/f help 2 for more &e&m--------------'
  '2':
    - '&e&m------------------&r&c&l Page 2 &e&m--------------------'
    - '&3/f home     &e>>  &7Teleport to faction home'
    - '&3/f sethome &e>>  &7Set your faction home'
    - '&3/f leave    &e>>  &7Leave your faction'
    - '&3/f invite    &e>>  &7Invite a player to your faction'
    - '&3/f deinvite &e>>  &7Revoke invitation to player'
    - '&e&m--------------&r &2/f help 3 for more &e&m--------------'
  '3':
    - '&e&m------------------&r&c&l Page 3 &e&m--------------------'
    - '&3/f claim     &e>>  &7Claim land'
    - '&3/f unclaim  &e>>  &7Unclaim land'
    - '&3/f kick      &e>>  &7Kick player from your faction'
    - '&3/f mod      &e>>  &7Set player role in faction'
    - '&3/f chat     &e>>  &7Switch to faction chat'
    - '&e&m--------------&r &2/f help 4 for more &e&m--------------'
  '4':
    - '&e&m------------------&r&c&l Page 4 &e&m--------------------'
    - '&3/f version &e>>  &7Display version information'
    - '&e&m--------------&r&2 End of /f help &e&m-----------------'
